# Generated by Django 5.2.12 on 2026-08-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designer', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(choices=[('champagne', 'Champagne'), ('midnight', 'Midnight'), ('blush', 'Blush'), ('ivory', 'Ivory'), ('sage', 'Sage'), ('noir', 'Noir'), ('dusty_rose', 'Dusty Rose'), ('ecru', 'Ecru')], max_length=50)),
                ('style', models.CharField(choices=[('ballgown', 'Ballgown'), ('column', 'Column'), ('a_line', 'A-Line'), ('mermaid', 'Mermaid')], max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='gowns/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_reserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
