# Generated by Django 5.2.12 on 2026-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_gown_size_customerprofile_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
    ]
