# Generated by Django 5.2.12 on 2026-08-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_staffprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gown',
            name='designer',
        ),
    ]
