# Generated by Django 5.2.12 on 2026-08-31 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_gown_designer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('prep', models.CharField(choices=[('pulled', 'Pulled'), ('reserved', 'Reserved'), ('cleaned', 'Cleaned'), ('ready', 'Ready')], default='pulled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_page.gown')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
