# Generated by Django 5.2.12 on 2026-09-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
