name: FashionCLIP Worker

on:
  workflow_dispatch:

jobs:
  fashionclip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fashion-clip==0.2.2
          pip install torch==2.13.0
          pip install transformers==4.30.2
          pip install numpy==1.26.4
          pip install Pillow==12.3.0

      - name: Run FashionCLIP worker
        run: |
          python fashionclip_worker/run_fashionclip.py

      - name: Upload embedding file
        uses: actions/upload-artifact@v4
        with:
          name: gown-embeddings
          path: fashionclip_worker/gown_embeddings.json